package main

import "fmt"

func main() {
	fmt.Println("----[SingleArrQueue]")
	aq := NewArrQueue(3)
	fmt.Println("----Push")
	aq.Push(0)
	aq.Push(1)
	aq.Push(2)
	aq.Push(3)
	fmt.Println("----Pop")
	aq.Pop()
	aq.Pop()
	aq.Pop()
	aq.Pop()
	fmt.Println("----Push")
	aq.Push(0)
	aq.Push(1)
	aq.Push(2)
	aq.Push(3)
	fmt.Println("----done")

	fmt.Println("----[SingleListQueue]")
	lq := NewListQueue()
	fmt.Println("----Push")
	lq.Push(0)
	lq.Push(1)
	lq.Push(2)
	lq.Push(3)
	fmt.Println("----Pop")
	lq.Pop()
	lq.Pop()
	lq.Pop()
	lq.Pop()
	fmt.Println("----Push")
	lq.Push(0)
	lq.Push(1)
	lq.Push(2)
	lq.Push(3)
	fmt.Println("----done")

	fmt.Println("----[CycleArrQueue]")
	caq := NewCycleArrQueue(3)
	fmt.Println("----Push")
	caq.Push(0)
	caq.Push(1)
	caq.Push(2)
	caq.Push(3)
	fmt.Println("----Pop")
	caq.Pop()
	caq.Pop()
	caq.Pop()
	caq.Pop()
	fmt.Println("----Push")
	caq.Push(0)
	caq.Push(1)
	caq.Push(2)
	caq.Push(3)
	fmt.Println("----done")

	fmt.Println("----[CycleListQueue]")
	clq := NewCycleListQueue()
	fmt.Println("----Push")
	clq.Push(0)
	clq.Push(1)
	clq.Push(2)
	clq.Push(3)
	fmt.Println("----Pop")
	clq.Pop()
	clq.Pop()
	clq.Pop()
	clq.Pop()
	fmt.Println("----Push")
	clq.Push(0)
	clq.Push(1)
	clq.Push(2)
	clq.Push(3)
	fmt.Println("----done")
}
